/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KanbanPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_PLUGIN_SETTINGS = {
  defaultLanes: ["To Do", "In Progress", "Done"],
  laneWidth: 272,
  showTags: true,
  showDates: true,
  showCheckboxes: true,
  autoSaveDelay: 500,
  language: "auto",
  boardTemplatePath: "",
  newlineKey: "shift+enter",
  timezone: "local"
};
var DEFAULT_BOARD_SETTINGS = {
  laneWidth: 272,
  showTags: true,
  showDates: true,
  showCheckboxes: true
};

// src/kanban-view.ts
var import_obsidian = require("obsidian");

// src/parser.ts
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}
function createItem(title) {
  return {
    id: generateId(),
    title: title.trim(),
    body: "",
    tags: extractTags(title),
    dueDate: extractDate(title),
    checked: false,
    archived: false,
    children: []
  };
}
function createLane(title) {
  return {
    id: generateId(),
    title: title.trim(),
    items: [],
    collapsed: false,
    wipLimit: 0
  };
}
function createBoard(laneNames) {
  return {
    lanes: laneNames.map((name) => createLane(name)),
    settings: { ...DEFAULT_BOARD_SETTINGS }
  };
}
function extractTags(text) {
  const matches = text.match(/#[^\s#]+/g);
  return matches ? matches.map((t2) => t2.slice(1)) : [];
}
function extractDate(text) {
  const atMatch = text.match(/@\{(\d{4}-\d{2}-\d{2})\}/);
  if (atMatch) return atMatch[1];
  const emojiMatch = text.match(/📅\s*(\d{4}-\d{2}-\d{2})/);
  if (emojiMatch) return emojiMatch[1];
  return null;
}
function parseMarkdown(content) {
  const board = {
    lanes: [],
    settings: { ...DEFAULT_BOARD_SETTINGS }
  };
  const lines = content.split("\n");
  let currentLane = null;
  let inFrontmatter = false;
  let inArchive = false;
  let itemStack = [];
  function getCurrentItem() {
    return itemStack.length > 0 ? itemStack[itemStack.length - 1][1] : null;
  }
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (i === 0 && line.trim() === "---") {
      inFrontmatter = true;
      continue;
    }
    if (inFrontmatter) {
      if (line.trim() === "---") {
        inFrontmatter = false;
        continue;
      }
      parseFrontmatterLine(line, board.settings);
      continue;
    }
    if (line.match(/^##\s+%%\s*Archive\s*%%/i)) {
      inArchive = true;
      currentLane = null;
      itemStack = [];
      continue;
    }
    if (inArchive) {
      const archiveLaneMatch = line.match(/^###\s+(.+)$/);
      if (archiveLaneMatch) {
        const laneTitle = archiveLaneMatch[1].trim();
        currentLane = board.lanes.find((l) => l.title === laneTitle) || null;
        if (!currentLane) {
          currentLane = createLane(laneTitle);
          board.lanes.push(currentLane);
        }
        itemStack = [];
        continue;
      }
      const parsed2 = parseCardLine(line, itemStack, currentLane, true);
      if (parsed2) {
        itemStack = parsed2;
        continue;
      }
      const cur2 = getCurrentItem();
      if (cur2 && line.match(/^\s{4}/) && line.trim().length > 0 && !line.match(/^\s*[-*]\s/)) {
        if (cur2.body) cur2.body += "\n";
        cur2.body += line.trim();
      }
      continue;
    }
    const headingMatch = line.match(/^##\s+(.+)$/);
    if (headingMatch) {
      currentLane = createLane(headingMatch[1]);
      board.lanes.push(currentLane);
      itemStack = [];
      continue;
    }
    const parsed = parseCardLine(line, itemStack, currentLane, false);
    if (parsed) {
      itemStack = parsed;
      continue;
    }
    const cur = getCurrentItem();
    if (cur && line.match(/^\s{4}|\t/) && line.trim().length > 0 && !line.match(/^\s*[-*]\s/)) {
      if (cur.body) cur.body += "\n";
      cur.body += line.trim();
      continue;
    }
    if (line.trim() === "") {
      itemStack = [];
    }
  }
  return board;
}
function parseCardLine(line, stack, currentLane, archived) {
  const match = line.match(/^(\s*)([-*])\s+(.+)$/);
  if (!match || !currentLane) return null;
  const indent = match[1].length;
  const rawText = match[3];
  const item = parseItemText(rawText);
  if (archived) item.archived = true;
  if (indent === 0) {
    currentLane.items.push(item);
    return [[0, item]];
  }
  const newStack = [...stack];
  while (newStack.length > 0 && newStack[newStack.length - 1][0] >= indent) {
    newStack.pop();
  }
  if (newStack.length > 0) {
    const parent = newStack[newStack.length - 1][1];
    parent.children.push(item);
  } else {
    currentLane.items.push(item);
  }
  newStack.push([indent, item]);
  return newStack;
}
function parseFrontmatterLine(line, settings) {
  const match = line.match(/^(\w[\w-]*):\s*(.+)$/);
  if (!match) return;
  const [, key, value] = match;
  switch (key) {
    case "lane-width":
      settings.laneWidth = parseInt(value, 10) || DEFAULT_BOARD_SETTINGS.laneWidth;
      break;
    case "show-tags":
      settings.showTags = value.trim() === "true";
      break;
    case "show-dates":
      settings.showDates = value.trim() === "true";
      break;
    case "show-checkboxes":
      settings.showCheckboxes = value.trim() === "true";
      break;
  }
}
function parseItemText(rawText) {
  let checked = false;
  let text = rawText;
  const checkboxMatch = text.match(/^\[([x ])\]\s*/i);
  if (checkboxMatch) {
    checked = checkboxMatch[1].toLowerCase() === "x";
    text = text.slice(checkboxMatch[0].length);
  }
  const item = createItem(text);
  item.checked = checked;
  return item;
}
function boardToMarkdown(board) {
  const lines = [];
  lines.push("---");
  lines.push("kanban-plugin: kanban-matsuo");
  lines.push(`lane-width: ${board.settings.laneWidth}`);
  lines.push(`show-tags: ${board.settings.showTags}`);
  lines.push(`show-dates: ${board.settings.showDates}`);
  lines.push(`show-checkboxes: ${board.settings.showCheckboxes}`);
  lines.push("---");
  lines.push("");
  for (const lane of board.lanes) {
    lines.push(`## ${lane.title}`);
    lines.push("");
    for (const item of lane.items) {
      if (item.archived) continue;
      serializeItem(item, lines, 0, board.settings.showCheckboxes);
    }
    lines.push("");
  }
  const archivedByLane = /* @__PURE__ */ new Map();
  for (const lane of board.lanes) {
    const archived = lane.items.filter((i) => i.archived);
    if (archived.length > 0) {
      archivedByLane.set(lane.title, archived);
    }
  }
  if (archivedByLane.size > 0) {
    lines.push("## %% Archive %%");
    lines.push("");
    for (const [laneTitle, items] of archivedByLane) {
      lines.push(`### ${laneTitle}`);
      lines.push("");
      for (const item of items) {
        serializeItem(item, lines, 0, board.settings.showCheckboxes);
      }
      lines.push("");
    }
  }
  return lines.join("\n");
}
function serializeItem(item, lines, depth, showCheckboxes) {
  const indent = "    ".repeat(depth);
  let line = `${indent}- `;
  if (showCheckboxes) {
    line += item.checked ? "[x] " : "[ ] ";
  }
  line += item.title;
  lines.push(line);
  if (item.body) {
    for (const bodyLine of item.body.split("\n")) {
      lines.push(`${indent}    ${bodyLine}`);
    }
  }
  for (const child of item.children) {
    serializeItem(child, lines, depth + 1, showCheckboxes);
  }
}

// src/lang/en.ts
var en = {
  // Board
  "board.kanban-board": "Kanban board",
  "board.search-cards": "Search cards...",
  "board.add-lane": "+ Add lane",
  "board.new-lane": "New lane",
  // Lane
  "lane.expand": "Expand lane",
  "lane.collapse": "Collapse lane",
  "lane.edit-title": "Edit lane title",
  "lane.options": "Lane options",
  "lane.set-wip-limit": "Set WIP limit",
  "lane.delete": "Delete lane",
  "lane.delete-confirm": "This lane has {{count}} card(s). Delete anyway?",
  // Card
  "card.add": "Add a card...",
  "card.add-to": "Add card to {{lane}}",
  "card.edit": "Edit",
  "card.edit-title": "Edit card title",
  "card.mark-complete": "Mark complete",
  "card.mark-incomplete": "Mark incomplete",
  "card.mark-as-complete": 'Mark "{{title}}" as complete',
  "card.mark-as-incomplete": 'Mark "{{title}}" as incomplete',
  "card.archive": "Archive",
  "card.move-to": 'Move to "{{lane}}"',
  "card.delete": "Delete",
  // Commands
  "command.create-new-board": "Create new board",
  "command.toggle-board-view": "Toggle board view",
  // Settings
  "settings.board-defaults": "Board defaults",
  "settings.default-lanes": "Default lanes",
  "settings.default-lanes-desc": "Comma-separated list of lane names for new boards.",
  "settings.lane-width": "Lane width",
  "settings.lane-width-desc": "Default width of each lane in pixels.",
  "settings.display": "Display",
  "settings.show-tags": "Show tags",
  "settings.show-tags-desc": "Display tags on cards.",
  "settings.show-dates": "Show dates",
  "settings.show-dates-desc": "Display due dates on cards.",
  "settings.show-checkboxes": "Show checkboxes",
  "settings.show-checkboxes-desc": "Display checkboxes on cards.",
  "settings.performance": "Performance",
  "settings.auto-save-delay": "Auto-save delay",
  "settings.auto-save-delay-desc": "Delay in milliseconds before auto-saving changes.",
  "settings.language": "Language",
  "settings.language-desc": "UI language for the plugin.",
  "settings.language-auto": "Auto (follow Obsidian)",
  // Modal
  "modal.wip-limit-title": "Set WIP limit",
  "modal.wip-limit-name": "WIP limit",
  "modal.wip-limit-desc": "Maximum cards in this lane (0 = unlimited).",
  "modal.wip-limit-label": "WIP limit value",
  "modal.save": "Save",
  "modal.cancel": "Cancel",
  "modal.delete-lane-title": "Delete lane",
  "modal.delete": "Delete",
  // Filter
  "filter.by-tag": "Filter by tag",
  "filter.by-date": "Filter by date",
  "filter.all": "All",
  "filter.overdue": "Overdue",
  "filter.today": "Today",
  "filter.this-week": "This week",
  "filter.no-date": "No date",
  "filter.clear": "Clear filter",
  // Card extra
  "card.create-note": "Create linked note",
  "card.open-note": "Open linked note",
  // Commands extra
  "command.add-card": "Add card to lane",
  "command.move-card": "Move card",
  // Lane drag
  "lane.drag-handle": "Drag to reorder lane",
  // Modal extra
  "modal.select-lane": "Select lane",
  "modal.select-card": "Select card",
  "modal.select-target-lane": "Select target lane",
  "modal.card-title": "Card title",
  // Template
  "command.create-from-template": "Create board from template",
  "settings.templates": "Templates",
  "settings.board-template": "Board template",
  "settings.board-template-desc": "Template file path for new boards.",
  // Input
  "settings.input": "Input",
  "settings.newline-key": "Newline key",
  "settings.newline-key-desc": "Key combination to insert a newline in card text.",
  // Timezone
  "settings.timezone": "Timezone for dates",
  "settings.timezone-desc": "Timezone used for date filters (today, this week, overdue).",
  "settings.timezone-local": "Local time",
  "settings.timezone-utc": "UTC",
  // Card editor modal
  "card-editor.title": "Edit card",
  "card-editor.card-title": "Title",
  "card-editor.card-title-placeholder": "Card title",
  "card-editor.tags": "Tags",
  "card-editor.tags-desc": "Comma-separated (e.g. bug, urgent, feature).",
  "card-editor.tags-placeholder": "bug, urgent",
  "card-editor.due-date": "Due date",
  "card-editor.due-date-desc": "YYYY-MM-DD format.",
  "card-editor.clear-date": "Clear",
  "card-editor.body": "Description",
  "card-editor.body-placeholder": "Card description (optional)",
  // Subtasks
  "subtask.add": "Add subtask",
  "subtask.add-placeholder": "New subtask...",
  "subtask.progress": "{{done}}/{{total}}",
  "subtask.promote": "Promote to card",
  "subtask.delete": "Delete subtask",
  "subtask.collapse-done": "Hide completed",
  "subtask.show-done": "Show completed"
};

// src/lang/ja.ts
var ja = {
  // Board
  "board.kanban-board": "\u30AB\u30F3\u30D0\u30F3\u30DC\u30FC\u30C9",
  "board.search-cards": "\u30AB\u30FC\u30C9\u3092\u691C\u7D22...",
  "board.add-lane": "+ \u30EC\u30FC\u30F3\u3092\u8FFD\u52A0",
  "board.new-lane": "\u65B0\u3057\u3044\u30EC\u30FC\u30F3",
  // Lane
  "lane.expand": "\u30EC\u30FC\u30F3\u3092\u5C55\u958B",
  "lane.collapse": "\u30EC\u30FC\u30F3\u3092\u6298\u308A\u305F\u305F\u3080",
  "lane.edit-title": "\u30EC\u30FC\u30F3\u540D\u3092\u7DE8\u96C6",
  "lane.options": "\u30EC\u30FC\u30F3\u306E\u64CD\u4F5C",
  "lane.set-wip-limit": "WIP\u5236\u9650\u3092\u8A2D\u5B9A",
  "lane.delete": "\u30EC\u30FC\u30F3\u3092\u524A\u9664",
  "lane.delete-confirm": "\u3053\u306E\u30EC\u30FC\u30F3\u306B\u306F {{count}} \u679A\u306E\u30AB\u30FC\u30C9\u304C\u3042\u308A\u307E\u3059\u3002\u524A\u9664\u3057\u307E\u3059\u304B\uFF1F",
  // Card
  "card.add": "\u30AB\u30FC\u30C9\u3092\u8FFD\u52A0...",
  "card.add-to": "{{lane}} \u306B\u30AB\u30FC\u30C9\u3092\u8FFD\u52A0",
  "card.edit": "\u7DE8\u96C6",
  "card.edit-title": "\u30AB\u30FC\u30C9\u306E\u30BF\u30A4\u30C8\u30EB\u3092\u7DE8\u96C6",
  "card.mark-complete": "\u5B8C\u4E86\u306B\u3059\u308B",
  "card.mark-incomplete": "\u672A\u5B8C\u4E86\u306B\u623B\u3059",
  "card.mark-as-complete": "\u300C{{title}}\u300D\u3092\u5B8C\u4E86\u306B\u3059\u308B",
  "card.mark-as-incomplete": "\u300C{{title}}\u300D\u3092\u672A\u5B8C\u4E86\u306B\u623B\u3059",
  "card.archive": "\u30A2\u30FC\u30AB\u30A4\u30D6",
  "card.move-to": "\u300C{{lane}}\u300D\u306B\u79FB\u52D5",
  "card.delete": "\u524A\u9664",
  // Commands
  "command.create-new-board": "\u65B0\u3057\u3044\u30DC\u30FC\u30C9\u3092\u4F5C\u6210",
  "command.toggle-board-view": "\u30DC\u30FC\u30C9\u8868\u793A\u3092\u5207\u308A\u66FF\u3048",
  // Settings
  "settings.board-defaults": "\u30DC\u30FC\u30C9\u306E\u521D\u671F\u8A2D\u5B9A",
  "settings.default-lanes": "\u30C7\u30D5\u30A9\u30EB\u30C8\u30EC\u30FC\u30F3",
  "settings.default-lanes-desc": "\u65B0\u3057\u3044\u30DC\u30FC\u30C9\u306E\u30EC\u30FC\u30F3\u540D\uFF08\u30AB\u30F3\u30DE\u533A\u5207\u308A\uFF09\u3002",
  "settings.lane-width": "\u30EC\u30FC\u30F3\u5E45",
  "settings.lane-width-desc": "\u5404\u30EC\u30FC\u30F3\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u5E45\uFF08\u30D4\u30AF\u30BB\u30EB\uFF09\u3002",
  "settings.display": "\u8868\u793A",
  "settings.show-tags": "\u30BF\u30B0\u3092\u8868\u793A",
  "settings.show-tags-desc": "\u30AB\u30FC\u30C9\u306B\u30BF\u30B0\u3092\u8868\u793A\u3057\u307E\u3059\u3002",
  "settings.show-dates": "\u65E5\u4ED8\u3092\u8868\u793A",
  "settings.show-dates-desc": "\u30AB\u30FC\u30C9\u306B\u671F\u65E5\u3092\u8868\u793A\u3057\u307E\u3059\u3002",
  "settings.show-checkboxes": "\u30C1\u30A7\u30C3\u30AF\u30DC\u30C3\u30AF\u30B9\u3092\u8868\u793A",
  "settings.show-checkboxes-desc": "\u30AB\u30FC\u30C9\u306B\u30C1\u30A7\u30C3\u30AF\u30DC\u30C3\u30AF\u30B9\u3092\u8868\u793A\u3057\u307E\u3059\u3002",
  "settings.performance": "\u30D1\u30D5\u30A9\u30FC\u30DE\u30F3\u30B9",
  "settings.auto-save-delay": "\u81EA\u52D5\u4FDD\u5B58\u306E\u9045\u5EF6",
  "settings.auto-save-delay-desc": "\u5909\u66F4\u5F8C\u306E\u81EA\u52D5\u4FDD\u5B58\u307E\u3067\u306E\u9045\u5EF6\uFF08\u30DF\u30EA\u79D2\uFF09\u3002",
  "settings.language": "\u8A00\u8A9E",
  "settings.language-desc": "\u30D7\u30E9\u30B0\u30A4\u30F3\u306EUI\u8A00\u8A9E\u3002",
  "settings.language-auto": "\u81EA\u52D5\uFF08Obsidian\u306B\u5F93\u3046\uFF09",
  // Modal
  "modal.wip-limit-title": "WIP\u5236\u9650\u306E\u8A2D\u5B9A",
  "modal.wip-limit-name": "WIP\u5236\u9650",
  "modal.wip-limit-desc": "\u3053\u306E\u30EC\u30FC\u30F3\u306E\u30AB\u30FC\u30C9\u4E0A\u9650\u6570\uFF080 = \u7121\u5236\u9650\uFF09\u3002",
  "modal.wip-limit-label": "WIP\u5236\u9650\u5024",
  "modal.save": "\u4FDD\u5B58",
  "modal.cancel": "\u30AD\u30E3\u30F3\u30BB\u30EB",
  "modal.delete-lane-title": "\u30EC\u30FC\u30F3\u306E\u524A\u9664",
  "modal.delete": "\u524A\u9664",
  // Filter
  "filter.by-tag": "\u30BF\u30B0\u3067\u7D5E\u308A\u8FBC\u307F",
  "filter.by-date": "\u65E5\u4ED8\u3067\u7D5E\u308A\u8FBC\u307F",
  "filter.all": "\u3059\u3079\u3066",
  "filter.overdue": "\u671F\u9650\u5207\u308C",
  "filter.today": "\u4ECA\u65E5",
  "filter.this-week": "\u4ECA\u9031",
  "filter.no-date": "\u65E5\u4ED8\u306A\u3057",
  "filter.clear": "\u30D5\u30A3\u30EB\u30BF\u3092\u89E3\u9664",
  // Card extra
  "card.create-note": "\u30EA\u30F3\u30AF\u5148\u30CE\u30FC\u30C8\u3092\u4F5C\u6210",
  "card.open-note": "\u30EA\u30F3\u30AF\u5148\u30CE\u30FC\u30C8\u3092\u958B\u304F",
  // Commands extra
  "command.add-card": "\u30EC\u30FC\u30F3\u306B\u30AB\u30FC\u30C9\u3092\u8FFD\u52A0",
  "command.move-card": "\u30AB\u30FC\u30C9\u3092\u79FB\u52D5",
  // Lane drag
  "lane.drag-handle": "\u30C9\u30E9\u30C3\u30B0\u3057\u3066\u30EC\u30FC\u30F3\u3092\u4E26\u3073\u66FF\u3048",
  // Modal extra
  "modal.select-lane": "\u30EC\u30FC\u30F3\u3092\u9078\u629E",
  "modal.select-card": "\u30AB\u30FC\u30C9\u3092\u9078\u629E",
  "modal.select-target-lane": "\u79FB\u52D5\u5148\u30EC\u30FC\u30F3\u3092\u9078\u629E",
  "modal.card-title": "\u30AB\u30FC\u30C9\u306E\u30BF\u30A4\u30C8\u30EB",
  // Template
  "command.create-from-template": "\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u304B\u3089\u30DC\u30FC\u30C9\u3092\u4F5C\u6210",
  "settings.templates": "\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8",
  "settings.board-template": "\u30DC\u30FC\u30C9\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8",
  "settings.board-template-desc": "\u65B0\u3057\u3044\u30DC\u30FC\u30C9\u4F5C\u6210\u6642\u306E\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u30D5\u30A1\u30A4\u30EB\u30D1\u30B9\u3002",
  // Input
  "settings.input": "\u5165\u529B",
  "settings.newline-key": "\u6539\u884C\u30AD\u30FC",
  "settings.newline-key-desc": "\u30AB\u30FC\u30C9\u306E\u30C6\u30AD\u30B9\u30C8\u5185\u3067\u6539\u884C\u3092\u633F\u5165\u3059\u308B\u30AD\u30FC\u306E\u7D44\u307F\u5408\u308F\u305B\u3002",
  // Timezone
  "settings.timezone": "\u65E5\u4ED8\u306E\u30BF\u30A4\u30E0\u30BE\u30FC\u30F3",
  "settings.timezone-desc": "\u65E5\u4ED8\u30D5\u30A3\u30EB\u30BF\uFF08\u4ECA\u65E5\u3001\u4ECA\u9031\u3001\u671F\u9650\u5207\u308C\uFF09\u3067\u4F7F\u7528\u3059\u308B\u30BF\u30A4\u30E0\u30BE\u30FC\u30F3\u3002",
  "settings.timezone-local": "\u30ED\u30FC\u30AB\u30EB\u6642\u9593",
  "settings.timezone-utc": "UTC",
  // Card editor modal
  "card-editor.title": "\u30AB\u30FC\u30C9\u3092\u7DE8\u96C6",
  "card-editor.card-title": "\u30BF\u30A4\u30C8\u30EB",
  "card-editor.card-title-placeholder": "\u30AB\u30FC\u30C9\u306E\u30BF\u30A4\u30C8\u30EB",
  "card-editor.tags": "\u30BF\u30B0",
  "card-editor.tags-desc": "\u30AB\u30F3\u30DE\u533A\u5207\u308A\uFF08\u4F8B: bug, urgent, feature\uFF09\u3002",
  "card-editor.tags-placeholder": "bug, urgent",
  "card-editor.due-date": "\u671F\u65E5",
  "card-editor.due-date-desc": "YYYY-MM-DD \u5F62\u5F0F\u3002",
  "card-editor.clear-date": "\u30AF\u30EA\u30A2",
  "card-editor.body": "\u8AAC\u660E",
  "card-editor.body-placeholder": "\u30AB\u30FC\u30C9\u306E\u8AAC\u660E\uFF08\u4EFB\u610F\uFF09",
  // Subtasks
  "subtask.add": "\u30B5\u30D6\u30BF\u30B9\u30AF\u3092\u8FFD\u52A0",
  "subtask.add-placeholder": "\u65B0\u3057\u3044\u30B5\u30D6\u30BF\u30B9\u30AF...",
  "subtask.progress": "{{done}}/{{total}}",
  "subtask.promote": "\u30AB\u30FC\u30C9\u306B\u6607\u683C",
  "subtask.delete": "\u30B5\u30D6\u30BF\u30B9\u30AF\u3092\u524A\u9664",
  "subtask.collapse-done": "\u5B8C\u4E86\u3092\u975E\u8868\u793A",
  "subtask.show-done": "\u5B8C\u4E86\u3092\u8868\u793A"
};

// src/lang/index.ts
var translations = {
  en,
  ja
};
var currentLocale = "auto";
function setLocale(locale) {
  currentLocale = locale;
}
function getResolvedLocale() {
  if (currentLocale === "auto") {
    const obsidianLang = document.documentElement.lang || navigator.language || "en";
    return obsidianLang.split("-")[0];
  }
  return currentLocale;
}
function t(key, vars) {
  const locale = getResolvedLocale();
  const dict = translations[locale] || translations["en"];
  let text = dict[key] || en[key] || key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), String(v));
    }
  }
  return text;
}

// src/kanban-view.ts
var KANBAN_VIEW_TYPE = "kanban-matsuo-view";
var KanbanView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.board = null;
    this.file = null;
    this.saveTimeout = null;
    this.boardEl = null;
    // Drag state (cards)
    this.draggedItem = null;
    this.draggedFromLane = null;
    this.dragPlaceholder = null;
    // Drag state (lanes)
    this.draggedLane = null;
    // Touch drag state
    this.touchStartY = 0;
    this.touchStartX = 0;
    // Filter state
    this.filterMode = "none";
    this.filterValue = "";
    // External change detection (counter to handle concurrent saves)
    this.ignoreModifyCount = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return KANBAN_VIEW_TYPE;
  }
  getDisplayText() {
    return this.file ? this.file.basename : t("board.kanban-board");
  }
  getIcon() {
    return "layout-dashboard";
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("kanban-matsuo-container");
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (this.ignoreModifyCount > 0) {
          this.ignoreModifyCount--;
          return;
        }
        if (file instanceof import_obsidian.TFile && this.file && file.path === this.file.path) {
          await this.loadFile(file);
        }
      })
    );
  }
  async onClose() {
    if (this.saveTimeout !== null) {
      window.clearTimeout(this.saveTimeout);
      this.saveTimeout = null;
    }
  }
  async loadFile(file) {
    this.file = file;
    const content = await this.app.vault.read(file);
    this.board = parseMarkdown(content);
    this.render();
  }
  /** Public accessor for commands in main.ts */
  getBoard() {
    return this.board;
  }
  /** Public accessor for commands in main.ts */
  getFile() {
    return this.file;
  }
  /** Get today's date string respecting timezone setting */
  getToday() {
    const tz = this.plugin.settings.timezone;
    if (tz === "local") {
      const now = /* @__PURE__ */ new Date();
      const y = now.getFullYear();
      const m = String(now.getMonth() + 1).padStart(2, "0");
      const d = String(now.getDate()).padStart(2, "0");
      return `${y}-${m}-${d}`;
    }
    const parts = new Intl.DateTimeFormat("en-CA", {
      timeZone: tz,
      year: "numeric",
      month: "2-digit",
      day: "2-digit"
    }).format(/* @__PURE__ */ new Date());
    return parts;
  }
  /** Save a board state and re-render (for use by commands in main.ts) */
  async saveBoard(board) {
    this.board = board;
    if (!this.file) return;
    this.ignoreModifyCount++;
    await this.app.vault.process(this.file, () => boardToMarkdown(board));
  }
  /** Re-render the view (for use by commands in main.ts) */
  refresh() {
    this.render();
  }
  scheduleSave() {
    if (this.saveTimeout !== null) {
      window.clearTimeout(this.saveTimeout);
    }
    this.saveTimeout = window.setTimeout(() => {
      this.save();
    }, this.plugin.settings.autoSaveDelay);
  }
  async save() {
    if (!this.board || !this.file) return;
    this.ignoreModifyCount++;
    const board = this.board;
    await this.app.vault.process(this.file, () => boardToMarkdown(board));
  }
  render() {
    if (!this.board) return;
    this.contentEl.empty();
    this.contentEl.addClass("kanban-matsuo-container");
    this.contentEl.setAttribute("role", "application");
    this.contentEl.setAttribute("aria-label", t("board.kanban-board"));
    const toolbar = this.contentEl.createDiv({ cls: "kanban-matsuo-toolbar" });
    this.renderToolbar(toolbar);
    this.boardEl = this.contentEl.createDiv({
      cls: "kanban-matsuo-board",
      attr: { "aria-live": "polite" }
    });
    for (const lane of this.board.lanes) {
      this.renderLane(this.boardEl, lane);
    }
    this.renderAddLaneButton(this.boardEl);
  }
  renderToolbar(container) {
    const searchInput = container.createEl("input", {
      cls: "kanban-matsuo-search",
      attr: {
        type: "text",
        placeholder: t("board.search-cards"),
        "aria-label": t("board.search-cards")
      }
    });
    searchInput.addEventListener("input", () => {
      this.filterMode = "none";
      this.filterValue = "";
      this.filterCards(searchInput.value);
    });
    const tagFilterBtn = container.createEl("button", {
      cls: "kanban-matsuo-filter-btn clickable-icon",
      attr: { "aria-label": t("filter.by-tag"), "data-tooltip-position": "top" }
    });
    (0, import_obsidian.setIcon)(tagFilterBtn, "tag");
    tagFilterBtn.addEventListener("click", (e) => this.showTagFilterMenu(e));
    const dateFilterBtn = container.createEl("button", {
      cls: "kanban-matsuo-filter-btn clickable-icon",
      attr: { "aria-label": t("filter.by-date"), "data-tooltip-position": "top" }
    });
    (0, import_obsidian.setIcon)(dateFilterBtn, "calendar");
    dateFilterBtn.addEventListener("click", (e) => this.showDateFilterMenu(e));
    if (this.filterMode !== "none") {
      const clearBtn = container.createEl("button", {
        cls: "kanban-matsuo-filter-clear clickable-icon",
        attr: { "aria-label": t("filter.clear"), "data-tooltip-position": "top" }
      });
      (0, import_obsidian.setIcon)(clearBtn, "x");
      clearBtn.addEventListener("click", () => {
        this.filterMode = "none";
        this.filterValue = "";
        this.render();
      });
    }
  }
  showTagFilterMenu(e) {
    if (!this.board) return;
    const menu = new import_obsidian.Menu();
    const allTags = /* @__PURE__ */ new Set();
    for (const lane of this.board.lanes) {
      for (const item of lane.items) {
        if (!item.archived) item.tags.forEach((tag) => allTags.add(tag));
      }
    }
    menu.addItem((mi) => mi.setTitle(t("filter.all")).setIcon("list").onClick(() => {
      this.filterMode = "none";
      this.filterValue = "";
      this.render();
    }));
    for (const tag of allTags) {
      menu.addItem((mi) => mi.setTitle(`#${tag}`).setIcon("tag").onClick(() => {
        this.filterMode = "tag";
        this.filterValue = tag;
        this.render();
      }));
    }
    this.showMenuAtEvent(menu, e);
  }
  showDateFilterMenu(e) {
    const menu = new import_obsidian.Menu();
    const items = [
      [t("filter.all"), "list", ""],
      [t("filter.overdue"), "alert-circle", "overdue"],
      [t("filter.today"), "calendar", "today"],
      [t("filter.this-week"), "calendar-range", "week"],
      [t("filter.no-date"), "calendar-off", "none"]
    ];
    for (const [title, icon, val] of items) {
      menu.addItem((mi) => mi.setTitle(title).setIcon(icon).onClick(() => {
        this.filterMode = val ? "date" : "none";
        this.filterValue = val;
        this.render();
      }));
    }
    this.showMenuAtEvent(menu, e);
  }
  isItemVisible(item) {
    if (item.archived) return false;
    if (this.filterMode === "none") return true;
    if (this.filterMode === "tag") return item.tags.includes(this.filterValue);
    if (this.filterMode === "date") {
      const today = this.getToday();
      switch (this.filterValue) {
        case "overdue":
          return item.dueDate !== null && item.dueDate < today;
        case "today":
          return item.dueDate === today;
        case "week": {
          if (!item.dueDate) return false;
          const now = /* @__PURE__ */ new Date(today + "T00:00:00");
          const day = now.getDay();
          const diffToMon = day === 0 ? -6 : 1 - day;
          const monday = new Date(now);
          monday.setDate(now.getDate() + diffToMon);
          const sunday = new Date(monday);
          sunday.setDate(monday.getDate() + 6);
          const fmt = (d) => {
            const y = d.getFullYear();
            const m = String(d.getMonth() + 1).padStart(2, "0");
            const dd = String(d.getDate()).padStart(2, "0");
            return `${y}-${m}-${dd}`;
          };
          return item.dueDate >= fmt(monday) && item.dueDate <= fmt(sunday);
        }
        case "none":
          return item.dueDate === null;
      }
    }
    return true;
  }
  renderLane(container, lane) {
    const laneEl = container.createDiv({
      cls: "kanban-matsuo-lane",
      attr: { "data-lane-id": lane.id, role: "region", "aria-label": lane.title }
    });
    laneEl.style.setProperty("--lane-width", `${this.board.settings.laneWidth}px`);
    const headerEl = laneEl.createDiv({ cls: "kanban-matsuo-lane-header" });
    const dragHandle = headerEl.createEl("button", {
      cls: "kanban-matsuo-lane-drag-handle clickable-icon",
      attr: { "aria-label": t("lane.drag-handle"), draggable: "true", "data-tooltip-position": "top" }
    });
    (0, import_obsidian.setIcon)(dragHandle, "grip-vertical");
    dragHandle.addEventListener("dragstart", (e) => {
      this.draggedLane = lane;
      laneEl.addClass("kanban-matsuo-lane-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", lane.id);
      }
    });
    dragHandle.addEventListener("dragend", () => {
      laneEl.removeClass("kanban-matsuo-lane-dragging");
      this.draggedLane = null;
    });
    laneEl.addEventListener("dragover", (e) => {
      if (this.draggedLane && this.draggedLane.id !== lane.id) {
        e.preventDefault();
        if (e.dataTransfer) e.dataTransfer.dropEffect = "move";
      }
    });
    laneEl.addEventListener("drop", (e) => {
      if (this.draggedLane && this.board) {
        e.preventDefault();
        const fromIdx = this.board.lanes.indexOf(this.draggedLane);
        const toIdx = this.board.lanes.indexOf(lane);
        if (fromIdx >= 0 && toIdx >= 0) {
          this.board.lanes.splice(fromIdx, 1);
          this.board.lanes.splice(toIdx, 0, this.draggedLane);
          this.render();
          this.scheduleSave();
        }
      }
    });
    this.setupTouchDrag(dragHandle, laneEl, lane);
    const collapseBtn = headerEl.createEl("button", {
      cls: "kanban-matsuo-collapse-btn clickable-icon",
      attr: { "aria-label": lane.collapsed ? t("lane.expand") : t("lane.collapse"), "data-tooltip-position": "top" }
    });
    (0, import_obsidian.setIcon)(collapseBtn, lane.collapsed ? "chevron-right" : "chevron-down");
    collapseBtn.addEventListener("click", () => {
      lane.collapsed = !lane.collapsed;
      this.render();
      this.scheduleSave();
    });
    const titleEl = headerEl.createEl("h3", {
      cls: "kanban-matsuo-lane-title",
      text: lane.title,
      attr: { "aria-label": t("lane.edit-title"), contenteditable: "true" }
    });
    titleEl.addEventListener("blur", () => {
      var _a;
      const newTitle = ((_a = titleEl.textContent) == null ? void 0 : _a.trim()) || lane.title;
      if (newTitle !== lane.title) {
        lane.title = newTitle;
        this.scheduleSave();
      }
    });
    titleEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.isComposing) {
        e.preventDefault();
        titleEl.blur();
      }
    });
    const countEl = headerEl.createSpan({
      cls: "kanban-matsuo-lane-count",
      text: `${lane.items.filter((i) => !i.archived).length}`
    });
    if (lane.wipLimit > 0) {
      const activeCount = lane.items.filter((i) => !i.archived).length;
      if (activeCount >= lane.wipLimit) countEl.addClass("kanban-matsuo-wip-exceeded");
      countEl.setText(`${activeCount}/${lane.wipLimit}`);
    }
    const menuBtn = headerEl.createEl("button", {
      cls: "kanban-matsuo-lane-menu clickable-icon",
      attr: { "aria-label": t("lane.options"), "data-tooltip-position": "top" }
    });
    (0, import_obsidian.setIcon)(menuBtn, "more-vertical");
    menuBtn.addEventListener("click", (e) => this.showLaneMenu(e, lane));
    if (!lane.collapsed) {
      const listEl = laneEl.createDiv({
        cls: "kanban-matsuo-card-list",
        attr: { "data-lane-id": lane.id, role: "list" }
      });
      listEl.addEventListener("dragover", (e) => {
        if (!this.draggedItem) return;
        e.preventDefault();
        if (e.dataTransfer) e.dataTransfer.dropEffect = "move";
        this.handleDragOver(e, listEl);
      });
      listEl.addEventListener("dragleave", () => this.removePlaceholder());
      listEl.addEventListener("drop", (e) => {
        if (!this.draggedItem) return;
        e.preventDefault();
        this.handleDrop(lane, listEl);
      });
      for (const item of lane.items) {
        if (this.isItemVisible(item)) this.renderCardTree(listEl, item, lane, 0);
      }
      this.renderAddCardInput(laneEl, lane);
    }
  }
  /**
   * Render a card and its children recursively, each as a separate card in the list.
   * Children are indented by depth level.
   */
  renderCardTree(container, item, lane, depth) {
    this.renderCard(container, item, lane, depth);
    for (const child of item.children) {
      if (this.isItemVisible(child)) {
        this.renderCardTree(container, child, lane, depth + 1);
      }
    }
  }
  renderCard(container, item, lane, depth) {
    const cardEl = container.createDiv({
      cls: "kanban-matsuo-card",
      attr: { "data-item-id": item.id, draggable: "true", role: "listitem", tabindex: "0", "aria-label": item.title }
    });
    if (depth > 0) {
      cardEl.addClass("kanban-matsuo-card-child");
      cardEl.style.setProperty("--card-depth", `${depth}`);
    }
    if (item.checked) cardEl.addClass("kanban-matsuo-card-checked");
    cardEl.addEventListener("dragstart", (e) => {
      this.draggedItem = item;
      this.draggedFromLane = lane;
      cardEl.addClass("kanban-matsuo-card-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", item.id);
      }
    });
    cardEl.addEventListener("dragend", () => {
      cardEl.removeClass("kanban-matsuo-card-dragging");
      this.draggedItem = null;
      this.draggedFromLane = null;
      this.removePlaceholder();
    });
    this.setupTouchDragCard(cardEl, item, lane);
    cardEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        this.openCardEditor(item, lane);
      } else if ((e.key === "Delete" || e.key === "Backspace") && e.shiftKey) {
        e.preventDefault();
        this.deleteItem(item, lane);
      }
    });
    cardEl.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showCardMenu(e, item, lane);
    });
    cardEl.addEventListener("click", (e) => {
      if (e.target.closest("input, a")) return;
      this.openCardEditor(item, lane);
    });
    if (this.board.settings.showCheckboxes) {
      const checkboxEl = cardEl.createEl("input", {
        cls: "kanban-matsuo-card-checkbox task-list-item-checkbox",
        attr: { type: "checkbox", "aria-label": item.checked ? t("card.mark-as-incomplete", { title: item.title }) : t("card.mark-as-complete", { title: item.title }) }
      });
      checkboxEl.checked = item.checked;
      checkboxEl.addEventListener("change", () => {
        item.checked = checkboxEl.checked;
        cardEl.toggleClass("kanban-matsuo-card-checked", item.checked);
        this.scheduleSave();
      });
    }
    const bodyEl = cardEl.createDiv({ cls: "kanban-matsuo-card-body" });
    const titleEl = bodyEl.createDiv({ cls: "kanban-matsuo-card-title" });
    const displayTitle = item.title.replace(/#[^\s#]+/g, "").replace(/@\{\d{4}-\d{2}-\d{2}\}/g, "").trim() || item.title;
    if (this.file) {
      import_obsidian.MarkdownRenderer.render(this.app, displayTitle, titleEl, this.file.path, this);
    } else {
      titleEl.setText(displayTitle);
    }
    titleEl.querySelectorAll("a.internal-link").forEach((linkEl) => {
      linkEl.addEventListener("mouseover", (e) => {
        var _a;
        const href = linkEl.getAttribute("href");
        if (href) {
          this.app.workspace.trigger("hover-link", {
            event: e,
            source: KANBAN_VIEW_TYPE,
            hoverParent: this,
            targetEl: linkEl,
            linktext: href,
            sourcePath: ((_a = this.file) == null ? void 0 : _a.path) || ""
          });
        }
      });
    });
    if (this.board.settings.showTags && item.tags.length > 0) {
      const tagsEl = bodyEl.createDiv({ cls: "kanban-matsuo-card-tags" });
      for (const tag of item.tags) {
        const tagSpan = tagsEl.createSpan({ cls: "kanban-matsuo-tag", text: `#${tag}` });
        tagSpan.addEventListener("click", (e) => {
          e.stopPropagation();
          this.filterMode = "tag";
          this.filterValue = tag;
          this.render();
        });
      }
    }
    if (this.board.settings.showDates && item.dueDate) {
      const dateEl = bodyEl.createDiv({ cls: "kanban-matsuo-card-date" });
      const today = this.getToday();
      if (item.dueDate < today) dateEl.addClass("kanban-matsuo-date-overdue");
      else if (item.dueDate === today) dateEl.addClass("kanban-matsuo-date-today");
      dateEl.setText(`\u{1F4C5} ${item.dueDate}`);
    }
    if (item.children.length > 0) {
      const { done, total } = this.countChildren(item.children);
      const progressEl = bodyEl.createDiv({ cls: "kanban-matsuo-subtask-progress" });
      const barOuter = progressEl.createDiv({ cls: "kanban-matsuo-progress-bar" });
      const barInner = barOuter.createDiv({ cls: "kanban-matsuo-progress-fill" });
      const pct = total > 0 ? done / total * 100 : 0;
      barInner.style.setProperty("--progress-pct", `${pct}%`);
      progressEl.createSpan({
        cls: "kanban-matsuo-progress-text",
        text: t("subtask.progress", { done, total })
      });
    }
  }
  countChildren(children) {
    let done = 0, total = 0;
    for (const c of children) {
      total++;
      if (c.checked) done++;
      const sub = this.countChildren(c.children);
      done += sub.done;
      total += sub.total;
    }
    return { done, total };
  }
  /** Setup touch drag for lane reorder (mobile) */
  setupTouchDrag(handle, el, lane) {
    let longPressTimer = null;
    let isDragging = false;
    handle.addEventListener("touchstart", (e) => {
      const touch = e.touches[0];
      this.touchStartX = touch.clientX;
      this.touchStartY = touch.clientY;
      longPressTimer = window.setTimeout(() => {
        isDragging = true;
        el.addClass("kanban-matsuo-touch-dragging");
        this.draggedLane = lane;
      }, 300);
    }, { passive: true });
    handle.addEventListener("touchmove", (e) => {
      if (!isDragging) {
        const touch = e.touches[0];
        if (Math.abs(touch.clientX - this.touchStartX) > 10 || Math.abs(touch.clientY - this.touchStartY) > 10) {
          if (longPressTimer !== null) {
            window.clearTimeout(longPressTimer);
            longPressTimer = null;
          }
        }
        return;
      }
      e.preventDefault();
    });
    handle.addEventListener("touchend", () => {
      if (longPressTimer !== null) {
        window.clearTimeout(longPressTimer);
        longPressTimer = null;
      }
      if (isDragging) {
        isDragging = false;
        el.removeClass("kanban-matsuo-touch-dragging");
        this.draggedLane = null;
      }
    }, { passive: true });
  }
  /** Setup touch drag for card (mobile) */
  setupTouchDragCard(cardEl, item, lane) {
    let longPressTimer = null;
    let isDragging = false;
    cardEl.addEventListener("touchstart", (e) => {
      const touch = e.touches[0];
      this.touchStartX = touch.clientX;
      this.touchStartY = touch.clientY;
      longPressTimer = window.setTimeout(() => {
        isDragging = true;
        cardEl.addClass("kanban-matsuo-touch-dragging");
        this.draggedItem = item;
        this.draggedFromLane = lane;
      }, 300);
    }, { passive: true });
    cardEl.addEventListener("touchmove", (e) => {
      if (!isDragging) {
        const touch = e.touches[0];
        if (Math.abs(touch.clientX - this.touchStartX) > 10 || Math.abs(touch.clientY - this.touchStartY) > 10) {
          if (longPressTimer !== null) {
            window.clearTimeout(longPressTimer);
            longPressTimer = null;
          }
        }
        return;
      }
      e.preventDefault();
    });
    cardEl.addEventListener("touchend", () => {
      if (longPressTimer !== null) {
        window.clearTimeout(longPressTimer);
        longPressTimer = null;
      }
      if (isDragging) {
        isDragging = false;
        cardEl.removeClass("kanban-matsuo-touch-dragging");
        this.draggedItem = null;
        this.draggedFromLane = null;
      }
    }, { passive: true });
  }
  isNewlineKey(e) {
    const key = this.plugin.settings.newlineKey;
    if (key === "shift+enter") return e.shiftKey && !e.ctrlKey && !e.altKey && !e.metaKey;
    if (key === "ctrl+enter") return (e.ctrlKey || e.metaKey) && !e.shiftKey && !e.altKey;
    if (key === "alt+enter") return e.altKey && !e.shiftKey && !e.ctrlKey && !e.metaKey;
    return false;
  }
  renderAddCardInput(laneEl, lane) {
    const inputContainer = laneEl.createDiv({ cls: "kanban-matsuo-add-card" });
    const textarea = inputContainer.createEl("textarea", {
      cls: "kanban-matsuo-add-card-input",
      attr: { placeholder: t("card.add"), "aria-label": t("card.add-to", { lane: lane.title }), rows: "1" }
    });
    textarea.addEventListener("input", () => {
      textarea.style.setProperty("--textarea-rows", "1");
      const scrollH = textarea.scrollHeight;
      textarea.style.setProperty("--textarea-height", `${scrollH}px`);
    });
    textarea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.isComposing) {
        if (this.isNewlineKey(e)) {
          return;
        }
        e.preventDefault();
        const value = textarea.value.trim();
        if (value) {
          lane.items.push(createItem(value));
          textarea.value = "";
          this.render();
          this.scheduleSave();
        }
      }
    });
  }
  renderAddLaneButton(container) {
    const addLaneEl = container.createDiv({ cls: "kanban-matsuo-add-lane" });
    const addBtn = addLaneEl.createEl("button", {
      cls: "kanban-matsuo-add-lane-btn",
      text: t("board.add-lane"),
      attr: { "aria-label": t("board.add-lane"), "data-tooltip-position": "top" }
    });
    addBtn.addEventListener("click", () => {
      this.board.lanes.push(createLane(t("board.new-lane")));
      this.render();
      this.scheduleSave();
      const laneEls = this.boardEl.querySelectorAll(".kanban-matsuo-lane-title");
      const lastTitle = laneEls[laneEls.length - 1];
      if (lastTitle) {
        lastTitle.focus();
        const range = document.createRange();
        range.selectNodeContents(lastTitle);
        const sel = window.getSelection();
        sel == null ? void 0 : sel.removeAllRanges();
        sel == null ? void 0 : sel.addRange(range);
      }
    });
  }
  // Drag state for indent detection
  handleDragOver(e, listEl) {
    if (!this.draggedItem) return;
    this.removePlaceholder();
    this.dragPlaceholder = listEl.createDiv({ cls: "kanban-matsuo-drop-placeholder" });
    this.dragPlaceholder.remove();
    const afterEl = this.getDragAfterElement(listEl, e.clientY);
    if (afterEl) listEl.insertBefore(this.dragPlaceholder, afterEl);
    else listEl.appendChild(this.dragPlaceholder);
    const aboveEl = this.getCardAbovePlaceholder(listEl);
    const aboveDepth = aboveEl ? this.getCardDepth(aboveEl) : -1;
    const listRect = listEl.getBoundingClientRect();
    const relativeX = e.clientX - listRect.left;
    let targetDepth = Math.max(0, Math.floor(relativeX / 60));
    targetDepth = Math.min(targetDepth, aboveDepth + 1);
    this.dragPlaceholder.style.setProperty("--card-depth", `${targetDepth}`);
    if (targetDepth > 0) {
      this.dragPlaceholder.addClass("kanban-matsuo-drop-placeholder-indented");
    } else {
      this.dragPlaceholder.removeClass("kanban-matsuo-drop-placeholder-indented");
    }
  }
  getCardAbovePlaceholder(listEl) {
    let lastCard = null;
    for (const child of Array.from(listEl.children)) {
      if (child === this.dragPlaceholder) break;
      if (child.classList.contains("kanban-matsuo-card")) lastCard = child;
    }
    return lastCard;
  }
  getCardDepth(el) {
    const depthStr = el.style.getPropertyValue("--card-depth");
    return depthStr ? parseInt(depthStr, 10) : 0;
  }
  getDragAfterElement(container, y) {
    const cards = Array.from(container.querySelectorAll(".kanban-matsuo-card:not(.kanban-matsuo-card-dragging)"));
    return cards.reduce(
      (acc, card) => {
        const box = card.getBoundingClientRect();
        const offset = y - box.top - box.height / 2;
        if (offset < 0 && offset > acc.offset) return { offset, el: card };
        return acc;
      },
      { offset: Number.NEGATIVE_INFINITY, el: null }
    ).el;
  }
  handleDrop(targetLane, listEl) {
    if (!this.draggedItem || !this.draggedFromLane || !this.board) return;
    this.removeItemRecursive(this.draggedFromLane.items, this.draggedItem);
    const targetDepth = this.dragPlaceholder ? parseInt(this.dragPlaceholder.style.getPropertyValue("--card-depth") || "0", 10) : 0;
    const flatList = this.buildFlatList(targetLane.items, 0);
    const cardsBefore = [];
    if (this.dragPlaceholder) {
      for (const child of Array.from(listEl.children)) {
        if (child === this.dragPlaceholder) break;
        if (child.classList.contains("kanban-matsuo-card")) {
          const id = child.getAttribute("data-item-id");
          if (id) cardsBefore.push(id);
        }
      }
    }
    if (targetDepth === 0) {
      const insertIdx = this.findTopLevelInsertIndex(targetLane, cardsBefore);
      targetLane.items.splice(insertIdx, 0, this.draggedItem);
    } else {
      let parentItem = null;
      for (let i = cardsBefore.length - 1; i >= 0; i--) {
        const entry = flatList.find((f) => f.item.id === cardsBefore[i]);
        if (entry && entry.depth < targetDepth) {
          parentItem = entry.item;
          break;
        }
      }
      if (parentItem) {
        const lastAboveId = cardsBefore[cardsBefore.length - 1];
        const lastAboveIdx = parentItem.children.findIndex((c) => c.id === lastAboveId);
        if (lastAboveIdx >= 0) {
          parentItem.children.splice(lastAboveIdx + 1, 0, this.draggedItem);
        } else {
          parentItem.children.push(this.draggedItem);
        }
      } else {
        targetLane.items.push(this.draggedItem);
      }
    }
    this.removePlaceholder();
    this.render();
    this.scheduleSave();
  }
  buildFlatList(items, depth) {
    const result = [];
    for (const item of items) {
      if (!item.archived) {
        result.push({ item, depth });
        result.push(...this.buildFlatList(item.children, depth + 1));
      }
    }
    return result;
  }
  findTopLevelInsertIndex(lane, cardsBefore) {
    if (cardsBefore.length === 0) return 0;
    const lastAboveId = cardsBefore[cardsBefore.length - 1];
    for (let i = lane.items.length - 1; i >= 0; i--) {
      const topItem = lane.items[i];
      if (this.containsId(topItem, lastAboveId)) {
        return i + 1;
      }
    }
    return lane.items.length;
  }
  containsId(item, id) {
    if (item.id === id) return true;
    return item.children.some((c) => this.containsId(c, id));
  }
  removePlaceholder() {
    if (this.dragPlaceholder) {
      this.dragPlaceholder.remove();
      this.dragPlaceholder = null;
    }
  }
  deleteItem(item, lane) {
    if (this.removeItemRecursive(lane.items, item)) {
      this.render();
      this.scheduleSave();
    }
  }
  /**
   * Recursively search and remove an item from a list or any children.
   */
  removeItemRecursive(items, target) {
    const index = items.indexOf(target);
    if (index >= 0) {
      items.splice(index, 1);
      return true;
    }
    for (const item of items) {
      if (this.removeItemRecursive(item.children, target)) return true;
    }
    return false;
  }
  /**
   * Check if an item is a child (not top-level in the lane).
   */
  isChildItem(item, lane) {
    return !lane.items.includes(item);
  }
  /**
   * Promote a child item to a top-level card in the lane.
   * Removes it from its parent's children first.
   */
  promoteItem(item, lane) {
    this.removeItemRecursive(lane.items, item);
    lane.items.push(item);
    this.render();
    this.scheduleSave();
  }
  showMenuAtEvent(menu, e) {
    if (e instanceof MouseEvent) menu.showAtMouseEvent(e);
    else if (e.target instanceof HTMLElement) {
      const rect = e.target.getBoundingClientRect();
      menu.showAtPosition({ x: rect.left, y: rect.bottom });
    }
  }
  showCardMenu(e, item, lane) {
    const menu = new import_obsidian.Menu();
    menu.addItem((mi) => mi.setTitle(t("card.edit")).setIcon("pencil").onClick(() => {
      this.openCardEditor(item, lane);
    }));
    menu.addItem((mi) => mi.setTitle(item.checked ? t("card.mark-incomplete") : t("card.mark-complete")).setIcon(item.checked ? "square" : "check-square").onClick(() => {
      item.checked = !item.checked;
      this.render();
      this.scheduleSave();
    }));
    menu.addItem((mi) => mi.setTitle(t("card.archive")).setIcon("archive").onClick(() => {
      item.archived = true;
      this.render();
      this.scheduleSave();
    }));
    menu.addItem((mi) => mi.setTitle(t("card.create-note")).setIcon("file-plus").onClick(async () => await this.createLinkedNote(item)));
    const wikilinkMatch = item.title.match(/\[\[([^\]]+)\]\]/);
    if (wikilinkMatch) {
      menu.addItem((mi) => mi.setTitle(t("card.open-note")).setIcon("file-text").onClick(async () => {
        var _a;
        await this.app.workspace.openLinkText(wikilinkMatch[1].split("|")[0], ((_a = this.file) == null ? void 0 : _a.path) || "");
      }));
    }
    menu.addSeparator();
    if (this.isChildItem(item, lane)) {
      menu.addItem((mi) => mi.setTitle(t("subtask.promote")).setIcon("arrow-up").onClick(() => this.promoteItem(item, lane)));
    }
    if (this.board) {
      for (const targetLane of this.board.lanes) {
        if (targetLane.id === lane.id) continue;
        menu.addItem((mi) => mi.setTitle(t("card.move-to", { lane: targetLane.title })).setIcon("arrow-right").onClick(() => {
          this.removeItemRecursive(lane.items, item);
          targetLane.items.push(item);
          this.render();
          this.scheduleSave();
        }));
      }
    }
    menu.addSeparator();
    menu.addItem((mi) => mi.setTitle(t("card.delete")).setIcon("trash").onClick(() => this.deleteItem(item, lane)));
    this.showMenuAtEvent(menu, e);
  }
  async createLinkedNote(item) {
    var _a, _b, _c;
    const cleanTitle = item.title.replace(/#[^\s#]+/g, "").replace(/@\{\d{4}-\d{2}-\d{2}\}/g, "").replace(/\[\[[^\]]+\]\]/g, "").trim();
    const noteName = cleanTitle || "Untitled";
    const folder = ((_b = (_a = this.file) == null ? void 0 : _a.parent) == null ? void 0 : _b.path) || "";
    const notePath = (0, import_obsidian.normalizePath)(folder ? `${folder}/${noteName}.md` : `${noteName}.md`);
    if (!this.app.vault.getAbstractFileByPath(notePath)) await this.app.vault.create(notePath, `# ${noteName}
`);
    if (!item.title.includes("[[")) {
      item.title = `${item.title} [[${noteName}]]`;
      this.render();
      this.scheduleSave();
    }
    await this.app.workspace.openLinkText(noteName, ((_c = this.file) == null ? void 0 : _c.path) || "");
  }
  showLaneMenu(e, lane) {
    const menu = new import_obsidian.Menu();
    menu.addItem((mi) => mi.setTitle(t("lane.set-wip-limit")).setIcon("alert-circle").onClick(() => new WipLimitModal(this.app, lane, (limit) => {
      lane.wipLimit = limit;
      this.render();
      this.scheduleSave();
    }).open()));
    menu.addSeparator();
    menu.addItem((mi) => mi.setTitle(t("lane.delete")).setIcon("trash").onClick(() => {
      const activeItems = lane.items.filter((i) => !i.archived).length;
      if (activeItems > 0) new ConfirmDeleteModal(this.app, lane.title, activeItems, () => this.performLaneDelete(lane)).open();
      else this.performLaneDelete(lane);
    }));
    this.showMenuAtEvent(menu, e);
  }
  performLaneDelete(lane) {
    if (!this.board) return;
    const index = this.board.lanes.indexOf(lane);
    if (index >= 0) {
      this.board.lanes.splice(index, 1);
      this.render();
      this.scheduleSave();
    }
  }
  openCardEditor(item, _lane) {
    new CardEditorModal(this.app, item, () => {
      this.render();
      this.scheduleSave();
    }).open();
  }
  filterCards(query) {
    var _a;
    const q = query.toLowerCase().trim();
    const cards = (_a = this.boardEl) == null ? void 0 : _a.querySelectorAll(".kanban-matsuo-card");
    if (!cards) return;
    cards.forEach((cardEl) => {
      var _a2;
      const match = !q || (((_a2 = cardEl.textContent) == null ? void 0 : _a2.toLowerCase()) || "").includes(q);
      cardEl.toggleClass("kanban-matsuo-card-hidden", !match);
    });
  }
};
var WipLimitModal = class extends import_obsidian.Modal {
  constructor(app, lane, onSubmit) {
    super(app);
    this.lane = lane;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: t("modal.wip-limit-title") });
    new import_obsidian.Setting(contentEl).setName(t("modal.wip-limit-name")).setDesc(t("modal.wip-limit-desc")).addText((text) => {
      text.setValue(String(this.lane.wipLimit || ""));
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.setAttribute("aria-label", t("modal.wip-limit-label"));
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") this.submit(text.getValue());
      });
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText(t("modal.save")).setCta().onClick(() => {
      const inp = contentEl.querySelector("input");
      this.submit((inp == null ? void 0 : inp.value) || "0");
    })).addButton((btn) => btn.setButtonText(t("modal.cancel")).onClick(() => this.close()));
  }
  submit(value) {
    this.onSubmit(parseInt(value, 10) || 0);
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ConfirmDeleteModal = class extends import_obsidian.Modal {
  constructor(app, _laneTitle, cardCount, onConfirm) {
    super(app);
    this.cardCount = cardCount;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: t("modal.delete-lane-title") });
    contentEl.createEl("p", { text: t("lane.delete-confirm", { count: this.cardCount }) });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText(t("modal.delete")).setWarning().onClick(() => {
      this.onConfirm();
      this.close();
    })).addButton((btn) => btn.setButtonText(t("modal.cancel")).onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CardEditorModal = class extends import_obsidian.Modal {
  constructor(app, item, onSave) {
    super(app);
    this.hideDone = false;
    this.item = item;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("kanban-matsuo-card-editor");
    contentEl.createEl("h3", { text: t("card-editor.title") });
    let titleValue = this.item.title.replace(/#[^\s#]+/g, "").replace(/@\{\d{4}-\d{2}-\d{2}\}/g, "").trim();
    const titleSetting = new import_obsidian.Setting(contentEl).setName(t("card-editor.card-title"));
    const titleInput = titleSetting.controlEl.createEl("textarea", {
      cls: "kanban-matsuo-editor-textarea",
      attr: {
        placeholder: t("card-editor.card-title-placeholder"),
        rows: "2",
        "aria-label": t("card-editor.card-title")
      }
    });
    titleInput.value = titleValue;
    const tagsSetting = new import_obsidian.Setting(contentEl).setName(t("card-editor.tags")).setDesc(t("card-editor.tags-desc"));
    const tagsInput = tagsSetting.controlEl.createEl("input", {
      cls: "kanban-matsuo-editor-input",
      attr: {
        type: "text",
        placeholder: t("card-editor.tags-placeholder"),
        "aria-label": t("card-editor.tags")
      }
    });
    tagsInput.value = this.item.tags.join(", ");
    const dateSetting = new import_obsidian.Setting(contentEl).setName(t("card-editor.due-date")).setDesc(t("card-editor.due-date-desc"));
    const dateInput = dateSetting.controlEl.createEl("input", {
      cls: "kanban-matsuo-editor-input",
      attr: {
        type: "date",
        "aria-label": t("card-editor.due-date")
      }
    });
    dateInput.value = this.item.dueDate || "";
    const bodySetting = new import_obsidian.Setting(contentEl).setName(t("card-editor.body"));
    const bodyInput = bodySetting.controlEl.createEl("textarea", {
      cls: "kanban-matsuo-editor-textarea",
      attr: {
        placeholder: t("card-editor.body-placeholder"),
        rows: "4",
        "aria-label": t("card-editor.body")
      }
    });
    bodyInput.value = this.item.body || "";
    this.renderSubTaskEditor(contentEl);
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText(t("modal.save")).setCta().onClick(() => {
        this.saveAndClose(titleInput, tagsInput, dateInput, bodyInput);
      });
    }).addButton((btn) => {
      btn.setButtonText(t("modal.cancel")).onClick(() => this.close());
    });
    titleInput.focus();
  }
  saveAndClose(titleEl, tagsEl, dateEl, bodyEl) {
    const title = titleEl.value.trim();
    if (!title) return;
    const tags = tagsEl.value.split(",").map((s) => s.trim().replace(/^#/, "")).filter((s) => s.length > 0);
    const dueDate = dateEl.value || null;
    let fullTitle = title;
    if (tags.length > 0) {
      fullTitle += " " + tags.map((tag) => `#${tag}`).join(" ");
    }
    if (dueDate) {
      fullTitle += ` @{${dueDate}}`;
    }
    this.item.title = fullTitle;
    this.item.tags = tags;
    this.item.dueDate = dueDate;
    this.item.body = bodyEl.value.trim();
    this.onSave(this.item);
    this.close();
  }
  renderSubTaskEditor(container) {
    const section = container.createDiv({ cls: "kanban-matsuo-subtask-editor" });
    const header = section.createDiv({ cls: "kanban-matsuo-subtask-header" });
    header.createEl("h4", { text: t("subtask.add"), cls: "kanban-matsuo-subtask-heading" });
    if (this.item.children.length > 0) {
      const toggleBtn = header.createEl("button", {
        cls: "kanban-matsuo-subtask-toggle clickable-icon",
        text: this.hideDone ? t("subtask.show-done") : t("subtask.collapse-done")
      });
      toggleBtn.addEventListener("click", () => {
        this.hideDone = !this.hideDone;
        this.rerenderSubTasks(section);
      });
    }
    this.renderSubTaskList(section, this.item.children, 0);
    const addRow = section.createDiv({ cls: "kanban-matsuo-subtask-add" });
    const addInput = addRow.createEl("input", {
      cls: "kanban-matsuo-editor-input",
      attr: { type: "text", placeholder: t("subtask.add-placeholder"), "aria-label": t("subtask.add") }
    });
    addInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.isComposing) {
        const val = addInput.value.trim();
        if (val) {
          const child = createItem(val);
          this.item.children.push(child);
          addInput.value = "";
          this.rerenderSubTasks(section);
        }
      }
    });
  }
  rerenderSubTasks(section) {
    section.empty();
    this.renderSubTaskEditor(section.parentElement);
    section.remove();
  }
  renderSubTaskList(container, items, depth) {
    const list = container.createDiv({ cls: "kanban-matsuo-subtask-list" });
    if (depth > 0) list.style.setProperty("--subtask-depth", `${depth}`);
    for (let i = 0; i < items.length; i++) {
      const child = items[i];
      if (this.hideDone && child.checked) continue;
      const row = list.createDiv({ cls: "kanban-matsuo-subtask-row" });
      const checkbox = row.createEl("input", {
        attr: { type: "checkbox", "aria-label": child.title },
        cls: "kanban-matsuo-subtask-checkbox"
      });
      checkbox.checked = child.checked;
      checkbox.addEventListener("change", () => {
        child.checked = checkbox.checked;
        row.toggleClass("kanban-matsuo-subtask-done", child.checked);
      });
      const titleEl = row.createSpan({
        cls: `kanban-matsuo-subtask-title${child.checked ? " kanban-matsuo-subtask-done" : ""}`,
        text: child.title
      });
      titleEl.contentEditable = "true";
      titleEl.addEventListener("blur", () => {
        var _a;
        const val = (_a = titleEl.textContent) == null ? void 0 : _a.trim();
        if (val) child.title = val;
      });
      const deleteBtn = row.createEl("button", {
        cls: "kanban-matsuo-subtask-delete clickable-icon",
        attr: { "aria-label": t("subtask.delete") }
      });
      (0, import_obsidian.setIcon)(deleteBtn, "x");
      deleteBtn.addEventListener("click", () => {
        items.splice(i, 1);
        const section = list.closest(".kanban-matsuo-subtask-editor");
        if (section) this.rerenderSubTasks(section);
      });
      if (child.checked) row.addClass("kanban-matsuo-subtask-done");
      if (child.children.length > 0) {
        this.renderSubTaskList(row, child.children, depth + 1);
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var KanbanSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName(t("settings.language")).setDesc(t("settings.language-desc")).addDropdown(
      (dropdown) => dropdown.addOption("auto", t("settings.language-auto")).addOption("en", "English").addOption("ja", "\u65E5\u672C\u8A9E").setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.board-defaults")).setHeading();
    new import_obsidian2.Setting(containerEl).setName(t("settings.default-lanes")).setDesc(t("settings.default-lanes-desc")).addText(
      (text) => text.setPlaceholder("To Do, In Progress, Done").setValue(this.plugin.settings.defaultLanes.join(", ")).onChange(async (value) => {
        this.plugin.settings.defaultLanes = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.lane-width")).setDesc(t("settings.lane-width-desc")).addText(
      (text) => text.setPlaceholder("272").setValue(String(this.plugin.settings.laneWidth)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (num > 0) {
          this.plugin.settings.laneWidth = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.display")).setHeading();
    new import_obsidian2.Setting(containerEl).setName(t("settings.show-tags")).setDesc(t("settings.show-tags-desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showTags).onChange(async (value) => {
        this.plugin.settings.showTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.show-dates")).setDesc(t("settings.show-dates-desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showDates).onChange(async (value) => {
        this.plugin.settings.showDates = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.show-checkboxes")).setDesc(t("settings.show-checkboxes-desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCheckboxes).onChange(async (value) => {
        this.plugin.settings.showCheckboxes = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.performance")).setHeading();
    new import_obsidian2.Setting(containerEl).setName(t("settings.auto-save-delay")).setDesc(t("settings.auto-save-delay-desc")).addText(
      (text) => text.setPlaceholder("500").setValue(String(this.plugin.settings.autoSaveDelay)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (num >= 100) {
          this.plugin.settings.autoSaveDelay = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.timezone")).setDesc(t("settings.timezone-desc")).addDropdown((dropdown) => {
      const zones = [
        ["local", t("settings.timezone-local")],
        ["UTC", "UTC (\xB10:00)"],
        ["Asia/Tokyo", "JST - \u65E5\u672C\u6A19\u6E96\u6642 (UTC+9)"],
        ["Asia/Shanghai", "CST - \u4E2D\u56FD\u6A19\u6E96\u6642 (UTC+8)"],
        ["Asia/Kolkata", "IST - \u30A4\u30F3\u30C9\u6A19\u6E96\u6642 (UTC+5:30)"],
        ["Asia/Seoul", "KST - \u97D3\u56FD\u6A19\u6E96\u6642 (UTC+9)"],
        ["Asia/Singapore", "SGT - \u30B7\u30F3\u30AC\u30DD\u30FC\u30EB (UTC+8)"],
        ["Asia/Bangkok", "ICT - \u30A4\u30F3\u30C9\u30B7\u30CA (UTC+7)"],
        ["Australia/Sydney", "AEST - \u30AA\u30FC\u30B9\u30C8\u30E9\u30EA\u30A2\u6771\u90E8 (UTC+10/11)"],
        ["Pacific/Auckland", "NZST - \u30CB\u30E5\u30FC\u30B8\u30FC\u30E9\u30F3\u30C9 (UTC+12/13)"],
        ["Europe/London", "GMT/BST - \u30ED\u30F3\u30C9\u30F3 (UTC+0/1)"],
        ["Europe/Paris", "CET/CEST - \u4E2D\u592E\u30E8\u30FC\u30ED\u30C3\u30D1 (UTC+1/2)"],
        ["Europe/Berlin", "CET/CEST - \u30D9\u30EB\u30EA\u30F3 (UTC+1/2)"],
        ["Europe/Moscow", "MSK - \u30E2\u30B9\u30AF\u30EF (UTC+3)"],
        ["America/New_York", "EST/EDT - \u7C73\u56FD\u6771\u90E8 (UTC-5/-4)"],
        ["America/Chicago", "CST/CDT - \u7C73\u56FD\u4E2D\u90E8 (UTC-6/-5)"],
        ["America/Denver", "MST/MDT - \u7C73\u56FD\u5C71\u5CB3\u90E8 (UTC-7/-6)"],
        ["America/Los_Angeles", "PST/PDT - \u7C73\u56FD\u592A\u5E73\u6D0B (UTC-8/-7)"],
        ["America/Sao_Paulo", "BRT - \u30D6\u30E9\u30B8\u30EB (UTC-3)"],
        ["Pacific/Honolulu", "HST - \u30CF\u30EF\u30A4 (UTC-10)"]
      ];
      for (const [value, label] of zones) {
        dropdown.addOption(value, label);
      }
      dropdown.setValue(this.plugin.settings.timezone).onChange(async (value) => {
        this.plugin.settings.timezone = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName(t("settings.input")).setHeading();
    new import_obsidian2.Setting(containerEl).setName(t("settings.newline-key")).setDesc(t("settings.newline-key-desc")).addDropdown(
      (dropdown) => dropdown.addOption("shift+enter", "Shift + Enter").addOption("ctrl+enter", "Ctrl + Enter").addOption("alt+enter", "Alt + Enter").setValue(this.plugin.settings.newlineKey).onChange(async (value) => {
        this.plugin.settings.newlineKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.templates")).setHeading();
    new import_obsidian2.Setting(containerEl).setName(t("settings.board-template")).setDesc(t("settings.board-template-desc")).addText(
      (text) => text.setPlaceholder("templates/kanban-template.md").setValue(this.plugin.settings.boardTemplatePath).onChange(async (value) => {
        this.plugin.settings.boardTemplatePath = value.trim();
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var LaneSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, lanes, onChoose) {
    super(app);
    this.lanes = lanes;
    this.onChoose = onChoose;
    this.setPlaceholder(t("modal.select-lane"));
  }
  getItems() {
    return this.lanes;
  }
  getItemText(item) {
    return item;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var CardSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, items, onChoose) {
    super(app);
    this.items = items;
    this.onChoose = onChoose;
    this.setPlaceholder(t("modal.select-card"));
  }
  getItems() {
    return this.items;
  }
  getItemText(item) {
    return `[${item.lane}] ${item.card}`;
  }
  onChooseItem(item) {
    this.onChoose(item.lane, item.card);
  }
};
var CardTitleModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder(t("modal.card-title"));
  }
  getItems() {
    return [];
  }
  getItemText(item) {
    return item;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
  // Override to allow submitting a free-form query
  selectSuggestion() {
    var _a, _b;
    const value = (_b = (_a = this.inputEl) == null ? void 0 : _a.value) != null ? _b : "";
    if (value.trim()) {
      this.close();
      this.onChoose(value.trim());
    }
  }
};
var KanbanPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_PLUGIN_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    setLocale(this.settings.language);
    this.registerView(KANBAN_VIEW_TYPE, (leaf) => new KanbanView(leaf, this));
    this.registerEvent(
      this.app.workspace.on("file-open", async (file) => {
        if (file instanceof import_obsidian3.TFile && await this.isKanbanFile(file)) {
          await this.openKanbanView(file);
        }
      })
    );
    this.addCommand({
      id: "create-new-board",
      name: t("command.create-new-board"),
      callback: async () => {
        await this.createNewBoard();
      }
    });
    this.addCommand({
      id: "create-from-template",
      name: t("command.create-from-template"),
      callback: async () => {
        await this.createNewBoard(true);
      }
    });
    this.addCommand({
      id: "toggle-board-view",
      name: t("command.toggle-board-view"),
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          if (!checking) {
            this.toggleKanbanView(file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "add-card-to-lane",
      name: t("command.add-card"),
      checkCallback: (checking) => {
        var _a;
        const file = this.app.workspace.getActiveFile();
        if (!file || !(file instanceof import_obsidian3.TFile)) return false;
        const leaves = this.app.workspace.getLeavesOfType(KANBAN_VIEW_TYPE);
        const activeView = (_a = leaves.find(
          (l) => {
            var _a2;
            return l.view instanceof KanbanView && ((_a2 = l.view.file) == null ? void 0 : _a2.path) === file.path;
          }
        )) == null ? void 0 : _a.view;
        if (!activeView) return false;
        if (!checking) {
          this.commandAddCardToLane(activeView);
        }
        return true;
      }
    });
    this.addCommand({
      id: "move-card",
      name: t("command.move-card"),
      checkCallback: (checking) => {
        var _a;
        const file = this.app.workspace.getActiveFile();
        if (!file || !(file instanceof import_obsidian3.TFile)) return false;
        const leaves = this.app.workspace.getLeavesOfType(KANBAN_VIEW_TYPE);
        const activeView = (_a = leaves.find(
          (l) => {
            var _a2;
            return l.view instanceof KanbanView && ((_a2 = l.view.file) == null ? void 0 : _a2.path) === file.path;
          }
        )) == null ? void 0 : _a.view;
        if (!activeView) return false;
        if (!checking) {
          this.commandMoveCard(activeView);
        }
        return true;
      }
    });
    this.addRibbonIcon("layout-dashboard", t("command.create-new-board"), async () => {
      await this.createNewBoard();
    });
    this.addSettingTab(new KanbanSettingTab(this.app, this));
    this.registerExtensions(["kanban"], KANBAN_VIEW_TYPE);
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle(t("command.create-new-board")).setIcon("layout-dashboard").onClick(async () => {
            var _a, _b;
            await this.createNewBoardInFolder(
              file instanceof import_obsidian3.TFile ? (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "" : file.path
            );
          });
        });
      })
    );
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_PLUGIN_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    setLocale(this.settings.language);
    const leaves = this.app.workspace.getLeavesOfType(KANBAN_VIEW_TYPE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof KanbanView) {
        const board = view.getBoard();
        if (board) {
          board.settings.laneWidth = this.settings.laneWidth;
          board.settings.showTags = this.settings.showTags;
          board.settings.showDates = this.settings.showDates;
          board.settings.showCheckboxes = this.settings.showCheckboxes;
          await view.saveBoard(board);
        }
        view.refresh();
      }
    }
  }
  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------
  /**
   * Check if a file is a kanban board by reading its frontmatter.
   */
  async isKanbanFile(file) {
    if (file.extension !== "md") return false;
    const content = await this.app.vault.read(file);
    return content.includes("kanban-plugin: kanban-matsuo");
  }
  /**
   * Open the kanban view for a given file.
   */
  async openKanbanView(file) {
    const existingLeaves = this.app.workspace.getLeavesOfType(KANBAN_VIEW_TYPE);
    for (const leaf2 of existingLeaves) {
      const view2 = leaf2.view;
      if (view2 instanceof KanbanView) {
        await view2.loadFile(file);
        this.app.workspace.revealLeaf(leaf2);
        return;
      }
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: KANBAN_VIEW_TYPE,
      active: true
    });
    const view = leaf.view;
    if (view instanceof KanbanView) {
      await view.loadFile(file);
    }
  }
  /**
   * Toggle between markdown and kanban view.
   */
  async toggleKanbanView(file) {
    const leaf = this.app.workspace.getMostRecentLeaf();
    if (!leaf) return;
    if (leaf.view instanceof KanbanView) {
      await leaf.setViewState({
        type: "markdown",
        state: { file: file.path }
      });
    } else {
      await this.openKanbanView(file);
    }
  }
  /**
   * Build the initial content for a new board.
   * If `useTemplate` is true and `boardTemplatePath` is configured, reads that
   * file as the template. Falls back to generating a default board.
   */
  async buildNewBoardContent(useTemplate) {
    if (useTemplate && this.settings.boardTemplatePath) {
      const templatePath = (0, import_obsidian3.normalizePath)(this.settings.boardTemplatePath);
      const templateFile = this.app.vault.getAbstractFileByPath(templatePath);
      if (templateFile instanceof import_obsidian3.TFile) {
        return await this.app.vault.read(templateFile);
      }
      new import_obsidian3.Notice(`Template not found: ${templatePath}`);
    }
    const board = createBoard(this.settings.defaultLanes);
    return boardToMarkdown(board);
  }
  /**
   * Create a new kanban board file, optionally using the configured template.
   */
  async createNewBoard(useTemplate = false) {
    var _a, _b;
    const activeFile = this.app.workspace.getActiveFile();
    const folder = activeFile ? (_b = (_a = activeFile.parent) == null ? void 0 : _a.path) != null ? _b : "" : "";
    await this.createNewBoardInFolder(folder, useTemplate);
  }
  /**
   * Create a new kanban board in a specific folder path.
   */
  async createNewBoardInFolder(folder, useTemplate = false) {
    const content = await this.buildNewBoardContent(useTemplate);
    const baseName = t("board.kanban-board");
    let fileName = `${baseName}.md`;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${folder}/${fileName}`))) {
      fileName = `${baseName} ${counter}.md`;
      counter++;
    }
    const filePath = (0, import_obsidian3.normalizePath)(folder ? `${folder}/${fileName}` : fileName);
    const file = await this.app.vault.create(filePath, content);
    if (file instanceof import_obsidian3.TFile) {
      await this.openKanbanView(file);
    }
  }
  /**
   * "Add card to lane" command implementation.
   * Opens a lane picker, then prompts for card title.
   */
  commandAddCardToLane(view) {
    const board = view.getBoard();
    if (!board) {
      new import_obsidian3.Notice(t("modal.select-lane"));
      return;
    }
    const laneNames = board.lanes.map((l) => l.title);
    if (laneNames.length === 0) return;
    new LaneSuggestModal(this.app, laneNames, (selectedLane) => {
      const cardModal = new CardTitleModal(this.app, async (cardTitle) => {
        if (!cardTitle) return;
        const lane = board.lanes.find((l) => l.title === selectedLane);
        if (!lane) return;
        const item = createItem(cardTitle);
        lane.items.push(item);
        await view.saveBoard(board);
        view.refresh();
      });
      cardModal.open();
    }).open();
  }
  /**
   * "Move card" command implementation.
   * Opens a card picker across all lanes, then a target lane picker.
   */
  commandMoveCard(view) {
    const board = view.getBoard();
    if (!board) return;
    const cardItems = [];
    for (const lane of board.lanes) {
      for (const item of lane.items) {
        if (!item.archived) {
          cardItems.push({ lane: lane.title, card: item.title });
        }
      }
    }
    if (cardItems.length === 0) return;
    new CardSuggestModal(this.app, cardItems, (sourceLaneName, cardTitle) => {
      const laneNames = board.lanes.map((l) => l.title);
      new LaneSuggestModal(this.app, laneNames, async (targetLaneName) => {
        if (sourceLaneName === targetLaneName) return;
        const sourceLane = board.lanes.find((l) => l.title === sourceLaneName);
        const targetLane = board.lanes.find((l) => l.title === targetLaneName);
        if (!sourceLane || !targetLane) return;
        const cardIndex = sourceLane.items.findIndex((i) => i.title === cardTitle);
        if (cardIndex === -1) return;
        const [movedCard] = sourceLane.items.splice(cardIndex, 1);
        targetLane.items.push(movedCard);
        await view.saveBoard(board);
        view.refresh();
      }).open();
    }).open();
  }
};
